#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Command-line interface for :mod:`introduction`.

This module gives the robotics ``introduction`` package a single package-level
entry point while preserving the existing script-level workflows:

1. Modern subcommand form::

       python -m introduction.cli manipulator --all --rich
       python -m introduction.cli mobius --backend plotly
       python -m introduction.cli kinematics --op cross --v1 1 2 3 --v2 4 5 6

2. Historical direct-script form remains available through the original files::

       python introduction/manipulator.py --all --rich
       python introduction/mobius.py --backend mpl
       python introduction/kinematics.py --op magnitude --v1 1 2 3

3. Compatibility no-subcommand form is routed heuristically when possible::

       python -m introduction.cli --backend mpl
       python -m introduction.cli --all --rich
       python -m introduction.cli --op magnitude --v1 1 2 3

The CLI also includes a ``sphinx-skel`` helper for generating a conservative,
GitHub Pages friendly Sphinx documentation skeleton.
"""
from __future__ import annotations

import argparse
import importlib
import importlib.util
import sys
from pathlib import Path
from typing import Callable, Iterable


# ---------- Import shim so `python cli.py` also works ----------
if __package__ in (None, ""):
    # Running as a script from introduction/: add repository root to sys.path.
    # introduction/cli.py -> repository root is one parent up.
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))


_PACKAGE = "introduction"
_PROJECT = "Robotics - introduction"
_AUTHOR = "Robotics"

_REQUIRED_MODULES = [
    "introduction.cli",
]

_OPTIONAL_MODULES = [
    "introduction.kinematics",
    "introduction.manipulator",
    "introduction.mobius",
    "introduction.mobius_mpl",
    "introduction.mobius_plotly",
    "introduction.mobius_pyvista",
]

_AUTODOC_MOCK_IMPORTS = [
    "matplotlib",
    "matplotlib.pyplot",
    "mpl_toolkits",
    "mpl_toolkits.mplot3d",
    "numpy",
    "plotly",
    "plotly.graph_objects",
    "pyfiglet",
    "pyvista",
    "rich",
    "rich.console",
    "rich.table",
    "scipy",
    "sympy",
    "yaml",
]


def _module_is_importable(module_name: str) -> bool:
    """Return ``True`` only when a module can actually be imported.

    ``importlib.util.find_spec`` can report that a module exists even when the
    module fails during import because an optional dependency is missing. Sphinx
    autodoc needs importable modules, so this helper performs the stricter check
    used by the generated API page.
    """
    try:
        if importlib.util.find_spec(module_name) is None:
            return False
        importlib.import_module(module_name)
    except Exception:
        return False
    return True


def _available_modules() -> list[str]:
    """Return package modules that are safe for Sphinx autodoc to import."""
    modules: list[str] = []
    for mod in [*_REQUIRED_MODULES, *_OPTIONAL_MODULES]:
        if _module_is_importable(mod):
            modules.append(mod)
    return modules


def _rst_heading(text: str, underline: str = "=") -> str:
    """Return a reStructuredText heading with a matching underline length."""
    return f"{text}\n{underline * len(text)}\n\n"


def _write_if_needed(path: Path, text: str, *, force: bool = False) -> bool:
    """Write ``text`` unless ``path`` already exists and overwrite is disabled."""
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _ensure_sphinx_support_dirs(dest: Path) -> None:
    """Create Sphinx support directories and tracked placeholder files."""
    for dirname in ("_templates", "_static"):
        folder = dest / dirname
        folder.mkdir(parents=True, exist_ok=True)
        gitkeep = folder / ".gitkeep"
        if not gitkeep.exists():
            gitkeep.write_text("", encoding="utf-8")


def _build_conf_py() -> str:
    """Build a conservative Sphinx ``conf.py`` for GitHub Pages deployments."""
    return f"""# Generated by {_PACKAGE}.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> introduction -> repository root
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

project = {_PROJECT!r}
author = {_AUTHOR!r}

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = {_AUTODOC_MOCK_IMPORTS!r}
napoleon_google_docstring = True
napoleon_numpy_docstring = True
"""


def _build_index_rst() -> str:
    """Build a Sphinx ``index.rst`` page with safe heading underline lengths."""
    title = f"Welcome to {_PACKAGE}'s documentation"
    return (
        f".. {_PACKAGE} documentation master file\n\n"
        + _rst_heading(title, "=")
        + "The ``introduction`` package contains robotics foundation examples for "
        + "manipulator geometry enumeration, vector and frame operations, vector "
        + "kinematics, and Mobius-strip visualization workflows.\n\n"
        + ".. toctree::\n"
        + "   :maxdepth: 2\n"
        + "   :caption: Contents:\n\n"
        + "   api\n"
        + "   usage\n"
    )


def _build_usage_rst() -> str:
    """Build a small usage page for package-level documentation."""
    return (
        _rst_heading("Usage", "=")
        + _rst_heading("Package CLI", "-")
        + "The package-level CLI delegates to the existing introduction modules::\n\n"
        + "   python -m introduction.cli manipulator --all --rich\n"
        + "   python -m introduction.cli mobius --backend plotly\n"
        + "   python -m introduction.cli kinematics --op cross --v1 1 2 3 --v2 4 5 6\n\n"
        + _rst_heading("Sphinx Skeleton", "-")
        + "Generate or refresh this documentation skeleton with::\n\n"
        + "   python -m introduction.cli sphinx-skel introduction/docs --force\n\n"
        + "The generated pages intentionally use conservative reStructuredText so they "
        + "remain friendly to GitHub Pages deployments.\n"
    )


def _build_api_rst() -> str:
    """Build an API page that includes only importable modules."""
    parts: list[str] = [_rst_heading("API Reference", "=")]
    modules = _available_modules()

    if not modules:
        parts.append(
            "No modules were importable when this API page was generated.\n\n"
            "Regenerate the Sphinx skeleton from an environment where the package "
            "can be imported, or install the package dependencies before building docs.\n"
        )
        return "".join(parts)

    for mod in modules:
        parts.append(_rst_heading(mod, "-"))
        parts.append(f".. automodule:: {mod}\n")
        parts.append("   :members:\n")
        parts.append("   :undoc-members:\n")
        parts.append("   :show-inheritance:\n\n")

    return "".join(parts)


def _build_makefile() -> str:
    """Build the minimal project-standard Sphinx Makefile."""
    return """# Minimal Sphinx Makefile
.PHONY: html clean
html:
	+sphinx-build -b html . _build/html
clean:
	+rm -rf _build
"""


def _write_sphinx_skeleton(dest: Path, *, force: bool = False) -> list[Path]:
    """Create or update a deploy-safe Sphinx documentation skeleton."""
    dest = dest.expanduser().resolve()
    dest.mkdir(parents=True, exist_ok=True)
    _ensure_sphinx_support_dirs(dest)

    files = {
        dest / "conf.py": _build_conf_py(),
        dest / "index.rst": _build_index_rst(),
        dest / "api.rst": _build_api_rst(),
        dest / "usage.rst": _build_usage_rst(),
        dest / "Makefile": _build_makefile(),
    }

    written: list[Path] = []
    for path, text in files.items():
        if _write_if_needed(path, text, force=force):
            written.append(path)
    return written


def _import_workflow_main(module_name: str) -> Callable[[list[str] | None], object]:
    """Import a workflow module and return a callable compatible with ``main(argv)``.

    The introduction scripts already own their argument parsers and solver
    behavior. This wrapper avoids duplicating those options in the package-level
    CLI while still giving the package a single command entry point for
    automation and documentation.
    """
    module = importlib.import_module(module_name)
    main_fn = getattr(module, "main", None)
    if main_fn is None or not callable(main_fn):
        raise RuntimeError(f"{module_name!r} does not expose a callable main().")
    return main_fn


def _run_module_main(module_name: str, argv: list[str]) -> int:
    """Run an existing introduction workflow module with the provided arguments."""
    main_fn = _import_workflow_main(module_name)
    result = main_fn(argv)
    if isinstance(result, int):
        return result
    return 0


def _run_sphinx_skel(args: argparse.Namespace) -> int:
    """Generate the Sphinx documentation skeleton."""
    written = _write_sphinx_skeleton(args.dest, force=args.force)

    print(f"Sphinx skeleton ready: {args.dest}")
    if written:
        print("Written files:")
        for path in written:
            print(f"  {path}")
    else:
        print("No existing files were overwritten. Use --force to regenerate.")

    print("Support files ensured:")
    print(f"  {args.dest / '_static' / '.gitkeep'}")
    print(f"  {args.dest / '_templates' / '.gitkeep'}")
    return 0


def _add_delegate_arguments(p: argparse.ArgumentParser, *, module_label: str) -> None:
    """Add pass-through arguments for a delegated workflow subcommand."""
    p.add_argument(
        "workflow_args",
        nargs=argparse.REMAINDER,
        help=(
            f"Arguments passed directly to introduction.{module_label}. "
            "Use '--' before options if your shell/parser treats them as parent options."
        ),
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the package-level command-line parser."""
    parser = argparse.ArgumentParser(
        prog="introduction",
        description=(
            "Package-level CLI for robotics introduction workflows and Sphinx "
            "documentation skeleton generation."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )

    sub = parser.add_subparsers(dest="cmd")

    skel = sub.add_parser(
        "sphinx-skel",
        help="create a deploy-safe Sphinx documentation skeleton for this package",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    skel.add_argument("dest", type=Path, help="Destination docs directory.")
    skel.add_argument("--force", action="store_true", help="Overwrite existing Sphinx skeleton files.")

    manipulator = sub.add_parser(
        "manipulator",
        help="delegate to introduction.manipulator",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_delegate_arguments(manipulator, module_label="manipulator")

    mobius = sub.add_parser(
        "mobius",
        help="delegate to introduction.mobius",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_delegate_arguments(mobius, module_label="mobius")

    kinematics = sub.add_parser(
        "kinematics",
        help="delegate to introduction.kinematics",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        allow_abbrev=False,
    )
    _add_delegate_arguments(kinematics, module_label="kinematics")

    return parser


_KINEMATICS_HINTS = {
    "--op",
    "--v1",
    "--v2",
    "--v3",
    "--Rmat",
    "--euler",
    "--order",
    "--radians",
    "--fx",
    "--fy",
    "--fz",
    "--params",
    "--t",
    "--t-grid",
    "--out-txt",
    "--out-csv",
}

_MOBIUS_HINTS = {
    "--backend",
    "--R",
    "--w",
    "--nu",
    "--nv",
    "--out",
    "--show",
}

_MANIPULATOR_HINTS = {
    "--all",
    "--j1",
    "--j2",
    "--j3",
    "--a12",
    "--a23",
    "--style",
    "--rich",
    "--figlet",
    "--count",
    "--export-json",
    "--export-csv",
}


def _argv_contains(argv: Iterable[str], hints: set[str]) -> bool:
    """Return ``True`` when any CLI token matches a known workflow option."""
    for token in argv:
        name = token.split("=", 1)[0]
        if name in hints:
            return True
    return False


def _route_legacy_no_subcommand(argv: list[str]) -> str | None:
    """Route compatibility no-subcommand usage to a workflow when possible.

    Ambiguous flags are intentionally resolved conservatively:
    - kinematics wins when ``--op`` or vector/function flags are present.
    - mobius wins when rendering geometry flags are present.
    - manipulator wins when manipulator enumeration flags are present.
    """
    if _argv_contains(argv, _KINEMATICS_HINTS):
        return "kinematics"
    if _argv_contains(argv, _MOBIUS_HINTS):
        return "mobius"
    if _argv_contains(argv, _MANIPULATOR_HINTS):
        return "manipulator"
    return None


def _strip_separator(args: list[str]) -> list[str]:
    """Remove a leading ``--`` separator from delegated argument lists."""
    if args and args[0] == "--":
        return args[1:]
    return args


def main(argv: list[str] | None = None) -> int:
    """Run the package-level ``introduction`` command-line interface."""
    raw_argv = list(sys.argv[1:] if argv is None else argv)

    # Historical compatibility: allow users to call the package-level CLI with
    # the original script options and route them to the most likely workflow.
    if raw_argv and raw_argv[0] not in {
        "sphinx-skel",
        "manipulator",
        "mobius",
        "kinematics",
        "-h",
        "--help",
    }:
        route = _route_legacy_no_subcommand(raw_argv)
        if route is None:
            parser = build_parser()
            parser.error(
                "Could not infer a workflow from no-subcommand arguments. "
                "Use one of: manipulator, mobius, kinematics, sphinx-skel."
            )
        raw_argv = [route, *raw_argv]

    parser = build_parser()
    args = parser.parse_args(raw_argv)

    if args.cmd == "sphinx-skel":
        return _run_sphinx_skel(args)

    if args.cmd == "manipulator":
        return _run_module_main("introduction.manipulator", _strip_separator(args.workflow_args))

    if args.cmd == "mobius":
        return _run_module_main("introduction.mobius", _strip_separator(args.workflow_args))

    if args.cmd == "kinematics":
        return _run_module_main("introduction.kinematics", _strip_separator(args.workflow_args))

    parser.print_help()
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
