from __future__ import annotations
import argparse, sys, numpy as np
from pathlib import Path
from .apis import AngularAPI

def numpy3(arg: str):
    vals = [float(x) for x in arg.split(",")]
    if len(vals) != 3: raise argparse.ArgumentTypeError("Expect 3 comma-separated floats.")
    return np.array(vals, float)

def numpy9(arg: str):
    vals = [float(x) for x in arg.split(",")]
    if len(vals) != 9: raise argparse.ArgumentTypeError("Expect 9 comma-separated floats.")
    return np.array(vals, float).reshape(3,3)

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="angular", description="Angular velocity toolkit CLI")
    sub = p.add_subparsers(dest="cmd", required=True)

    # from-euler
    s = sub.add_parser("from-euler", help="Build rotation from Euler angles")
    s.add_argument("--order", required=True, help="e.g., ZYX")
    s.add_argument("--angles", required=True, type=numpy3, help="phi,theta,psi (rad)")
    s.add_argument("--save", help="filename.npy in angular/out")

    # omega-from-Rdot
    s = sub.add_parser("omega-from-Rdot", help="Compute ω̃ = Rdot R^T")
    s.add_argument("--R", required=True, type=numpy9)
    s.add_argument("--Rdot", required=True, type=numpy9)

    # Rdot-from-omega
    s = sub.add_parser("Rdot-from-omega", help="Compute Rdot = ω̃ R")
    s.add_argument("--R", required=True, type=numpy9)
    s.add_argument("--omega", required=True, type=numpy3)

    # velocity-matrix
    s = sub.add_parser("velocity-matrix", help="Compute V = Tdot T^{-1}")
    s.add_argument("--R", required=True, type=numpy9)
    s.add_argument("--d", required=True, type=numpy3)
    s.add_argument("--Rdot", required=True, type=numpy9)
    s.add_argument("--ddot", required=True, type=numpy3)

    # rigid-point-velocity
    s = sub.add_parser("rigid-pt-vel", help="Compute vP = ω×(rP-dB)+dBdot")
    s.add_argument("--omega", required=True, type=numpy3)
    s.add_argument("--rP", required=True, type=numpy3)
    s.add_argument("--dB", required=True, type=numpy3)
    s.add_argument("--dBdot", required=True, type=numpy3)

    # screw-from-twist
    s = sub.add_parser("screw-from-twist", help="Decompose 6×1 twist into axis/moment/pitch")
    s.add_argument("--twist", required=True, type=lambda s: np.array([float(x) for x in s.split(",")], float))

    # ---------------- Sphinx docs skeleton ----------------
    sk = sub.add_parser("sphinx-skel", help="Create/refresh Sphinx docs skeleton in angular/docs")
    sk.add_argument("dest", nargs="?", default="angular/docs",
                    help="Destination docs dir (default: angular/docs)")
    sk.add_argument("--force", action="store_true", help="Overwrite existing files if present")

    return p

def _write(path: Path, text: str, *, force: bool) -> None:
    if not path.exists() or force:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

def main(argv=None):
    api = AngularAPI()
    ns = build_parser().parse_args(argv)
    if ns.cmd == "from-euler":
        R = api.rotation_from_euler(ns.order, tuple(ns.angles)).R
        if ns.save: api.persist_rotation(ns.save, R)
        print(R)
    elif ns.cmd == "omega-from-Rdot":
        print(api.omega_from_Rdot(ns.R, ns.Rdot))
    elif ns.cmd == "Rdot-from-omega":
        print(api.Rdot_from_omega(ns.R, ns.omega))
    elif ns.cmd == "velocity-matrix":
        print(api.velocity_matrix(ns.R, ns.d, ns.Rdot, ns.ddot))
    elif ns.cmd == "rigid-pt-vel":
        print(api.rigid_point_velocity(ns.omega, ns.rP, ns.dB, ns.dBdot))
    elif ns.cmd == "screw-from-twist":
        screw = api.screw_from_twist(ns.twist)
        print({"s": screw.s.tolist(), "m": screw.m.tolist(), "pitch": float(screw.pitch)})
    elif ns.cmd == "sphinx-skel":
        dest = Path(ns.dest)
        dest.mkdir(parents=True, exist_ok=True)
        # Minimal, matching forward's successful approach
        conf = (
            '# Generated by angular.cli\n'
            'project = "angular"\n'
            'extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon", "sphinx.ext.viewcode"]\n'
            'templates_path = ["_templates"]\n'
            'exclude_patterns = []\n'
            'html_theme = "furo"\n'
        )
        index = (
            ".. angular documentation master file\n\n"
            "Welcome to angular's docs!\n"
            "==========================\n\n"
            ".. toctree::\n"
            "   :maxdepth: 2\n"
            "   :caption: Contents:\n\n"
            "   api\n"
        )
        api_rst = (
            "API Reference\n"
            "=============\n\n"
            ".. automodule:: angular.app\n   :members:\n   :undoc-members:\n\n"
            ".. automodule:: angular.core\n   :members:\n   :undoc-members:\n\n"
            ".. automodule:: angular.design\n   :members:\n   :undoc-members:\n\n"
            ".. automodule:: angular.io\n   :members:\n   :undoc-members:\n\n"
            ".. automodule:: angular.utils\n   :members:\n   :undoc-members:\n\n"
            ".. automodule:: angular.tools.diagram\n   :members:\n   :undoc-members:\n"
        )
        makefile = (
            "# Minimal Sphinx Makefile\n"
            ".PHONY: html clean\n"
            "html:\n\t+sphinx-build -b html . _build/html\n"
            "clean:\n\t+rm -rf _build\n"
        )
        _write(dest / "conf.py", conf, force=ns.force)
        _write(dest / "index.rst", index, force=ns.force)
        _write(dest / "api.rst", api_rst, force=ns.force)
        _write(dest / "Makefile", makefile, force=ns.force)
        (dest / "_templates").mkdir(exist_ok=True)
        (dest / "_static").mkdir(exist_ok=True)
        print(str(dest))

if __name__ == "__main__":
    main()
