# Generated by rotation_kinematics.rot_cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> rotation_kinematics -> repository root
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

project = 'Robotics - rotation_kinematics'
author = 'Robotics'

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = ['matplotlib', 'matplotlib.pyplot', 'numpy', 'scipy', 'scipy.spatial', 'scipy.spatial.transform', 'sympy', 'yaml']
napoleon_google_docstring = True
napoleon_numpy_docstring = True
