# Generated by introduction.cli
from __future__ import annotations

import sys
from pathlib import Path

# docs -> introduction -> repository root
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

project = 'Robotics - introduction'
author = 'Robotics'

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "furo"
html_static_path = ["_static"]

autodoc_typehints = "description"
autodoc_mock_imports = ['matplotlib', 'matplotlib.pyplot', 'mpl_toolkits', 'mpl_toolkits.mplot3d', 'numpy', 'plotly', 'plotly.graph_objects', 'pyfiglet', 'pyvista', 'rich', 'rich.console', 'rich.table', 'scipy', 'sympy', 'yaml']
napoleon_google_docstring = True
napoleon_numpy_docstring = True
